create-mechanic improvements
designsystemsinternational/mechanic pull request #175
Opened 2023-05-05 17:16 UTC by fdoflorenzano

A bunch of pending improvements for create-mechanic! (Update: also contains a fix for dev and build commands)

- `dev` and `build` prompts have the functions and inputs folders paths as options to specify when running, but it was set up to have default values which would fallback to those values at the prompt level. That meant that the script didn't actually get whenever the command didn't get the option set up at all. Because of this, the script wouldn't take the value specified in the project's config at all. I removed this default fallback at the prompt level, so the config is taken into account. The eventual fallback still exists if the config doesn't specify folder paths.
- The most important that has been pending, this tweaks how design function templates and examples are managed, so that it also supports copying functions with custom inputs! The directory structure was changed to make this easier, so you'll see a lot of moved files. Each design function base has a directory with a `function/` folder (design function source code), a `dependencies.json` file (with a list of dependencies for the DF), and may have an `inputs/` folder with any custom inputs the DF uses.
- The previous change allows us to finally add the Adaptive Grid example @munusshih made a while ago! It used a custom input, and it will soon be able to replicate it for mechanic users across! Thanks again for this @munusshih! The other examples you made will be added as soon as possible too.
- Now create will also add an .gitignore file to a new project. As well as try to initialize a new git repository. This is a little improvemene that will make creating DFs and posting to GitHub more easy and quick.
- Added a little detail for the installing section. The cli asks users if they want to install dependencies, and now it will also list which dependencies are being installed.
- Added some line breaks across different sections to make the CLI output more readable.

<img width="981" alt="Screenshot 2023-05-05 at 13 15 00" src="https://user-images.githubusercontent.com/13511560/236523671-963c20bf-6d25-4c77-a010-bd66e5ceee4d.png">
<img width="980" alt="Screenshot 2023-05-05 at 13 15 18" src="https://user-images.githubusercontent.com/13511560/236523681-241c5272-dc81-4d6c-935c-083402b7e4b8.png">

2023-05-10 16:22 UTC, lucasdinonolte commented on packages/create-mechanic/function-examples/adaptive-grid/function/assets/FuturaStd-Bold.otf
This should probably replaced by an open source font.

Hate to recommend poppins, but I think we can get away visually with replacing it with Poppins :blush:

Other alternatives could be

- https://fonts.google.com/specimen/Jost
- https://fonts.google.com/specimen/League+Spartan

2023-05-10 18:49 UTC, munusshih commented on packages/create-mechanic/function-examples/adaptive-grid/function/assets/FuturaStd-Bold.otf
Oh yah tots agree. I remember I was only using Futura, because that was what was used on the original logo. But we should definitely replace it by an open source font.

<img width="676" alt="Screenshot 2023-05-10 at 2 48 09 PM" src="https://github.com/designsystemsinternational/mechanic/assets/34775424/723e2d71-3bd4-469a-ab53-8bfcf4b9468f">

2023-06-23 22:29 UTC, fdoflorenzano commented on packages/create-mechanic/function-examples/adaptive-grid/function/assets/FuturaStd-Bold.otf
Sorry that this took so long for me to get back to! But I finally did! 

Great catch @lucasdinonolte! Funnily enough, the one example selected to add here didn't actually use Futura. So for now it's enough to just remove the file and unused declaration.

Tho in the near future where we do add the other examples, we would need to replace Futura. @munusshih Do you have any font replacement preference for it? Lucas linked to some nice alternatives.

2023-06-23 22:30 UTC, fdoflorenzano commented
I also went ahead and cleaned up some other unused CSS declarations, and formatted some files that weren't before.

2025-05-06 19:14 UTC, lucasdinonolte reviewed
Very nice, left some comments. I'm not sure how much the added example function is meant to be reviewed, so feel free to ignore the comments made on the example function.

The only thing I really found is that I think this is missing to pull the inputs path from the mechanic config, so potentially copying any custom inputs to an unexpected folder.

2025-05-06 19:14 UTC, lucasdinonolte commented on packages/create-mechanic/function-examples/adaptive-grid/inputs/group/style.module.css
> +}
Should we box the group's content off a bit more visually? I had a hard time understanding what the custom component does initially.

2025-05-06 19:14 UTC, lucasdinonolte commented on packages/create-mechanic/function-examples/adaptive-grid/function/index.js
> +  showMultipleExports: true
When exporting this as a PNG the image that's rendered in the preview by default doesn't show up. When I upload a custom image it works.
![grid-2025-05-06-21-09 (1)](https://github.com/user-attachments/assets/98640370-ad92-4db9-b1f5-378999c105ff)
![grid-2025-05-06-21-09](https://github.com/user-attachments/assets/fb667009-99c5-472f-b6c0-4ca5feb83c39)

2025-05-06 19:14 UTC, lucasdinonolte commented on packages/create-mechanic/function-examples/adaptive-grid/function/index.js
> +        showGrid={grid}
I think this could be a cool use case for the `isPreview` argument that's passed to a design function now, as — if I understand correctly — the grid should probably not be included in the export.

2025-05-08 21:45 UTC, fdoflorenzano commented on packages/create-mechanic/new-function.js
> +    const projectInputDir = path.join(projectDir, "inputs");
Great catch! Fixed this and did some tweaks on the script to reflect the awareness of the folders. 

This made me realized too that dev and build didn't take the config paths into account because the values always defaulted in the prompt level, so the fallback to config never made it there. I added a fix for this.

2025-05-08 21:45 UTC, fdoflorenzano commented on packages/create-mechanic/function-examples/adaptive-grid/function/index.js
> +        showGrid={grid}
Good idea! Added :)

2025-05-08 21:45 UTC, fdoflorenzano commented on packages/create-mechanic/function-examples/adaptive-grid/function/index.js
> +  showMultipleExports: true
Thanks URL loading. Switched it to load the image directly.

2025-05-08 21:45 UTC, fdoflorenzano commented on packages/create-mechanic/function-examples/adaptive-grid/inputs/group/style.module.css
> +}
Any suggestions? I added a bit of padding so the nested relationship is more clear.

2025-05-09 03:44 UTC, munusshih commented
So happy to see that you guys are still working on this :)! Let me know if there's anything I can do to help.

2025-05-09 10:57 UTC, fdoflorenzano commented
> So happy to see that you guys are still working on this :)! Let me know if there's anything I can do to help.

omg thanks @munusshih! Sorry it took us this long to continue working on this. We've been busy, but now we're pushing to get it out :) I think we've got it covered, but we'll let you know if anything comes up.

2025-05-21 13:54 UTC, lucasdinonolte requested changes
Shaping up nicely! Just found one small thing around a missing dependency of the new function-example.

2025-05-21 13:54 UTC, lucasdinonolte commented on packages/create-mechanic/function-examples/adaptive-grid/dependencies.json
> +    "@mechanic-design/engine-react": "^2.0.0-beta.10"
Do we need to add `@mechanic-design/ui-components` here as well?

I tested this locally by adding this function to the DSI Logo maker and had to install `@mechanic-design/ui-components` manually, as the app would crash otherwise.

2025-06-16 16:02 UTC, fdoflorenzano commented on packages/create-mechanic/function-examples/adaptive-grid/inputs/group/style.module.css
> +}
Thanks for this! I did a tweak to be closer to this.

2025-06-16 16:02 UTC, fdoflorenzano commented on packages/create-mechanic/function-examples/adaptive-grid/dependencies.json
> +    "@mechanic-design/engine-react": "^2.0.0-beta.10"
Great catch! I replicated it and go to the error too. Should be fixed now.

2025-07-04 11:17 UTC, lucasdinonolte approved these changes
Amaaaaaaazing

2025-07-04 16:24 UTC, merged